# frozen_string_literal: true

b1 = Brewery.create name: 'Koff', year: 1897
b2 = Brewery.create name: 'Malmgard', year: 2001
b3 = Brewery.create name: 'Weihenstephaner', year: 1040

s1 = Style.create name: 'Hefeweizen', description: 'A south German style of wheat beer (weissbier) typically made with a ratio of 50 percent barley to 50 percent wheat. Sometimes the percentage of wheat is even higher. "Hefe" means "with yeast," hence the beer\'s unfiltered and cloudy appearance. The particular ale yeast used produces unique esters and phenols of banana and cloves with an often dry and tart edge, some spiciness, and notes of bubblegum or apples. Hefeweizens are typified by little hop bitterness, and a moderate level of alcohol. Often served with a lemon wedge (popularized by Americans), to cut the wheat or yeasty edge, some may find this to be either a flavorful snap or an insult that can damage the beer\'s taste and head retention.'
s2 = Style.create name: 'European Pale Lager', description: 'Similar to Munich Helles, many European countries reacted to the popularity of early pale lagers by brewing their own. Hop flavor is significant and of noble varieties, bitterness is moderate, and both are backed by a solid malt body and sweet notes from an all-malt base.'
s3 = Style.create name: 'American Pale Ale', description: 'Originally British in origin, this style is now popular worldwide and the use of local or imported ingredients produces variances in character from region to region. American versions tend to be cleaner and hoppier (with the piney, citrusy Cascade variety appearing frequently) than British versions, which are usually more malty, buttery, aromatic, and balanced. Pale Ales range in color from deep gold to medium amber. Fruity esters and diacetyl can vary from none to moderate, and hop aroma can range from lightly floral to bold and pungent. In general, expect a good balance of caramel malt and expressive hops with a medium body and a mildly bitter finish.'
s4 = Style.create name: 'English IPA', description: 'Historically, English breweries exported a variety of beer styles to colonies across the British empire. But shipping ales to troops stationed in India was a particular challenge in an age when the journey took months and every cask contained wild Brettanomyces yeast. To withstand the voyage, Pale Ales were tweaked to be maltier, higher in alcohol content, and hoppier, as hops are a natural preservative. Historians believe that India Pale Ale (IPA) was then watered down for the troops, while officers and the elite would savor the beer at full strength. Over time, taxation has caused the English IPA to assume a lower alcohol. The leaner the brew the less malt is required, and less is the need for a strong hop presence, which would easily put the brew out of balance. Expect earthy, floral English hop character and a malt profile defined by notes of biscuit, toast, and toffee.'
s5 = Style.create name: 'English Porter', description: 'Porter is said to have been popular with transportation workers of Central London, hence the name. Most traditional British brewing documentation from the 1700\'s states that Porter was a blend of three different styles: an old ale (stale or soured), a new ale (brown or pale ale) and a weak one (mild ale), with various combinations of blending and staleness. The end result was also commonly known as "Entire Butt" or "Three Threads" and had a pleasing taste of neither new nor old. It was the first truly engineered beer, catering to the public\'s taste, playing a critical role in quenching the thirst of the UK\'s Industrial Revolution and contributing to the rise of today\'s mega-breweries. Porter saw a comeback in the US during the homebrewing and micro-brewery revolution of the late 1970\'s and early 80\'s and modern-day Porters are typically brewed using a pale malt base with the addition of black malt, crystal, chocolate, or smoked brown malt. While uncommon, roasted malt is occasionally added too. Some brewers will also age their beers after inoculation with live bacteria to create an authentic taste of the past. Hop bitterness is moderate on the whole and the color ranges from brown to black. Overall, English Porters remain very complex and interesting beers.'
s6 = Style.create name: 'Lowalcohol', description: 'A beer without or with a small amount of alcohol'

b1.beers.create name: 'Iso 3', style_id: s2.id
b1.beers.create name: 'Karhu', style_id: s2.id
b1.beers.create name: 'Tuplahumala', style_id: s2.id
b2.beers.create name: 'Huvila Pale Ale', style_id: s3.id
b2.beers.create name: 'X Porter', style_id: s5.id
b3.beers.create name: 'Hefeweizen', style_id: s6.id
b3.beers.create name: 'Helles', style_id: s2.id